---
name: end to end example pipeline

permissions:
  contents: read
  checks: write
  id-token: write

on: [push]

jobs:
  unit-tests:
    uses: ./.github/workflows/pytest.yml
    with:
      name: unit-tests
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      name: "Build backend"
      image_url: t1mon1106/integation-as-code
      docker_filename: ./backend/Dockerfile
      docker_context: ./backend/
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD : ${{ secrets.DOCKER_PASSWORD }}

