---
name: build hash_calculator

permissions:
  contents: read
  checks: write
  id-token: write

on: [push]

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      name: "Build calculator"
      image_url: t1mon1106/hash-calculator
      docker_filename: ./hash_calculator/Dockerfile
      docker_context: ./hash_calculator
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD : ${{ secrets.DOCKER_PASSWORD }}
