---
name: run wihout test-containers 

permissions:
  contents: read
  checks: write
  id-token: write

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_DBNAME: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      hash-calculator:
        image: t1mon1106/hash-calculator:main
        env:
          host: 0.0.0.0
          port: 8080

    steps:

      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.4
      - name: Install poetry dep
        run: cd ./backend && poetry install --no-root
      - name: run test with bash script
        run: cd ./backend && poetry run pytest -k old_approach
        env:
          db_drivername: "postgresql"
          db_username: "postgres"
          db_password: "postgres"
          db_name: "postgres"
          db_host: "postgres"
          db_port: "5432"
          hash_service: "http://hash-calculator:8080"

  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      name: "Build backend"
      image_url: t1mon1106/integation-as-code
      docker_filename: ./backend/Dockerfile
      docker_context: ./backend/
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD : ${{ secrets.DOCKER_PASSWORD }}

