name: Unit tests

on:
  workflow_call:
    inputs:
      name:
        type: "string"
        required: true

jobs:
  unit-tests:
    name: "${{ inputs.name }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        poetry-version: ["1.8.4"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install poetry dep
        run: cd ./backend && poetry install --no-root
      - name: Run the automated tests (for example)
        run: poetry run pytest -v
